### ISSUE TITLE
java.lang.OutOfMemoryError and maxed out CPU usage

### ISSUE THREAD

**Issue by stefan2718** [keyboardDrummer/cloudformation-ide-tooling#16]
Very interested in using this project, but when I opened it for an existing template I had, it started maxing out all my CPU (on a MacBook Pro 2017) and then crashing with an OutOfMemoryError. 

Here is the zipped template file: [app-environment.cfn.yaml.zip](https://github.com/keyboardDrummer/cloudformation-ide-tooling/files/5460984/app-environment.cfn.yaml.zip)
Here are the logs:
```
[INFO] Found built-in jar.
[INFO] Using Miksilo mode JVM at /Library/Java/JavaVirtualMachines/adoptopenjdk-13.jdk/Contents/Home/bin/java with jar /Users/username/.vscode/extensions/keyboarddrummer.vscode-cloudformation-0.0.21/out/CloudFormationLanguageServer.jar
[INFO] Connection time was 2353
[INFO] Creating caching parser for uri file:///Users/username/projects/path/app-environment.cfn.yaml

[ERROR] Notification handler failed with: java.lang.OutOfMemoryError: Java heap space
 Stack trace:java.lang.OutOfMemoryError: Java heap space
	at miksilo.editorParser.parsers.editorParsers.ParseResults$.singleResult(ParseResults.scala:61)
	at miksilo.editorParser.parsers.editorParsers.DelayedParseResult.flatMapReady(ReadyParseResult.scala:57)
	at miksilo.editorParser.parsers.editorParsers.ParseResults.$anonfun$flatMapReady$1(ParseResults.scala:48)
	at miksilo.editorParser.parsers.editorParsers.ParseResults$$Lambda$521/0x0000000800e67040.apply(Unknown Source)
	at miksilo.editorParser.parsers.editorParsers.SRCons.flatMap(ParseResults.scala:94)
	at miksilo.editorParser.parsers.editorParsers.SRCons.$anonfun$flatMap$1(ParseResults.scala:106)
	at miksilo.editorParser.parsers.editorParsers.SRCons$$Lambda$527/0x0000000800e6a040.apply(Unknown Source)
	at miksilo.editorParser.parsers.editorParsers.SRCons.tail$lzycompute(ParseResults.scala:78)
	at miksilo.editorParser.parsers.editorParsers.SRCons.tail(ParseResults.scala:78)
	at miksilo.editorParser.parsers.editorParsers.SRCons.flatMap(ParseResults.scala:100)
	at miksilo.editorParser.parsers.editorParsers.SRCons.flatMap(ParseResults.scala:100)
	at miksilo.editorParser.parsers.editorParsers.SRCons.flatMap(ParseResults.scala:100)
	at miksilo.editorParser.parsers.editorParsers.SRCons.flatMap(ParseResults.scala:100)
	at miksilo.editorParser.parsers.editorParsers.SRCons.flatMap(ParseResults.scala:100)
	at miksilo.editorParser.parsers.editorParsers.SRCons.flatMap(ParseResults.scala:100)
	at miksilo.editorParser.parsers.editorParsers.SRCons.flatMap(ParseResults.scala:100)
	at miksilo.editorParser.parsers.editorParsers.SRCons.flatMap(ParseResults.scala:100)
	at miksilo.editorParser.parsers.editorParsers.SRCons.flatMap(ParseResults.scala:100)
	at miksilo.editorParser.parsers.editorParsers.SRCons.flatMap(ParseResults.scala:100)
	at miksilo.editorParser.parsers.editorParsers.ParseResults.mapResult(ParseResults.scala:26)
	at miksilo.editorParser.parsers.editorParsers.ParseResults.mapResult$(ParseResults.scala:25)
	at miksilo.editorParser.parsers.editorParsers.SRCons.mapResult(ParseResults.scala:64)
	at miksilo.editorParser.parsers.editorParsers.ParseResults.mapWithHistory(ParseResults.scala:39)
	at miksilo.editorParser.parsers.editorParsers.ParseResults.mapWithHistory$(ParseResults.scala:37)
	at miksilo.editorParser.parsers.editorParsers.SRCons.mapWithHistory(ParseResults.scala:64)
	at miksilo.editorParser.parsers.editorParsers.DelayedParseResult.$anonfun$mapWithHistory$1(ReadyParseResult.scala:47)
	at miksilo.editorParser.parsers.editorParsers.DelayedParseResult$$Lambda$559/0x0000000800e7f040.apply(Unknown Source)
	at miksilo.editorParser.parsers.editorParsers.DelayedParseResult.getResults(ReadyParseResult.scala:39)
	at miksilo.editorParser.parsers.editorParsers.DelayedParseResult.$anonfun$flatMapReady$1(ReadyParseResult.scala:58)
	at miksilo.editorParser.parsers.editorParsers.DelayedParseResult$$Lambda$550/0x0000000800e79c40.apply(Unknown Source)
	at miksilo.editorParser.parsers.editorParsers.DelayedParseResult.getResults(ReadyParseResult.scala:39)
	at miksilo.editorParser.parsers.editorParsers.DelayedParseResult.$anonfun$mapReady$1(ReadyParseResult.scala:52)
```

I also tested out the demo template that you have here: https://keyboarddrummer.github.io/cloudformation-ide-tooling/yaml.html
It worked perfectly fine, so my only guess is that the size of my template (only 37 resources) was too much to handle, or maybe there was some sort of accidental infinite loop that ate up all the CPU and Heap?

Let me know if there's any more info needed to help debug, as I'd really love to be able to use this, it seems super sleek!

**Comment by keyboardDrummer** [comment]
Hi @stefan2718, thank you for reporting this issue and providing all the right resources to debug it. I have a fix for it but I won't be able to deploy it in the coming days due to a busy schedule (I'm moving!).

**Comment by stefan2718** [comment]
Ah, best wishes for your move! Thanks for investigating ☺️
